// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiT0f3nLvq1nqoiGw5Iz2oPuYNRDHsOxU',
    appId: '1:584202681104:web:893990622cefc730e2c395',
    messagingSenderId: '584202681104',
    projectId: 'reddit-clone-86f36',
    authDomain: 'reddit-clone-86f36.firebaseapp.com',
    storageBucket: 'reddit-clone-86f36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuLcnt9j8boSnA2uM0ZnZj6-_gwhv6Mn0',
    appId: '1:584202681104:android:98e44aff7f2edc41e2c395',
    messagingSenderId: '584202681104',
    projectId: 'reddit-clone-86f36',
    storageBucket: 'reddit-clone-86f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2HB67dHtW0qhzP25xo0zxE11k7uMeZIk',
    appId: '1:584202681104:ios:a7af0fb8be98ec7fe2c395',
    messagingSenderId: '584202681104',
    projectId: 'reddit-clone-86f36',
    storageBucket: 'reddit-clone-86f36.appspot.com',
    iosClientId: '584202681104-usjvo5sbckik5vi0k478abdehsulut3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
